package com.krader.app.model;
// Generated Aug 8, 2018 2:18:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChapterDetailId generated by hbm2java
 */
@Embeddable
public class ChapterDetailId implements java.io.Serializable {

	private int idChapter;
	private String img;

	public ChapterDetailId() {
	}

	public ChapterDetailId(int idChapter, String img) {
		this.idChapter = idChapter;
		this.img = img;
	}

	@Column(name = "id_chapter", nullable = false)
	public int getIdChapter() {
		return this.idChapter;
	}

	public void setIdChapter(int idChapter) {
		this.idChapter = idChapter;
	}

	@Column(name = "img", nullable = false)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChapterDetailId))
			return false;
		ChapterDetailId castOther = (ChapterDetailId) other;

		return (this.getIdChapter() == castOther.getIdChapter()) && ((this.getImg() == castOther.getImg())
				|| (this.getImg() != null && castOther.getImg() != null && this.getImg().equals(castOther.getImg())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdChapter();
		result = 37 * result + (getImg() == null ? 0 : this.getImg().hashCode());
		return result;
	}

}
