package com.krader.app.model;
// Generated Aug 8, 2018 2:18:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MangaAuthorId generated by hbm2java
 */
@Embeddable
public class MangaAuthorId implements java.io.Serializable {

	private int idManga;
	private int idAuthor;

	public MangaAuthorId() {
	}

	public MangaAuthorId(int idManga, int idAuthor) {
		this.idManga = idManga;
		this.idAuthor = idAuthor;
	}

	@Column(name = "id_manga", nullable = false)
	public int getIdManga() {
		return this.idManga;
	}

	public void setIdManga(int idManga) {
		this.idManga = idManga;
	}

	@Column(name = "id_author", nullable = false)
	public int getIdAuthor() {
		return this.idAuthor;
	}

	public void setIdAuthor(int idAuthor) {
		this.idAuthor = idAuthor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MangaAuthorId))
			return false;
		MangaAuthorId castOther = (MangaAuthorId) other;

		return (this.getIdManga() == castOther.getIdManga()) && (this.getIdAuthor() == castOther.getIdAuthor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdManga();
		result = 37 * result + this.getIdAuthor();
		return result;
	}

}
