package com.krader.app.model;
// Generated Aug 8, 2018 2:18:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manga generated by hbm2java
 */
@Entity
@Table(name = "manga", catalog = "ComicDB")
public class Manga implements java.io.Serializable {

	private Integer idManga;
	private String nameManga;
	private String description;
	private String preImage;

	public Manga() {
	}

	public Manga(String nameManga, String preImage) {
		this.nameManga = nameManga;
		this.preImage = preImage;
	}

	public Manga(String nameManga, String description, String preImage) {
		this.nameManga = nameManga;
		this.description = description;
		this.preImage = preImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_manga", unique = true, nullable = false)
	public Integer getIdManga() {
		return this.idManga;
	}

	public void setIdManga(Integer idManga) {
		this.idManga = idManga;
	}

	@Column(name = "name_manga", nullable = false)
	public String getNameManga() {
		return this.nameManga;
	}

	public void setNameManga(String nameManga) {
		this.nameManga = nameManga;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "preImage", nullable = false)
	public String getPreImage() {
		return this.preImage;
	}

	public void setPreImage(String preImage) {
		this.preImage = preImage;
	}

}
