package com.krader.app.model;
// Generated Aug 9, 2018 3:31:01 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReaderManga generated by hbm2java
 */
@Entity
@Table(name = "reader_manga", catalog = "ComicDB")
public class ReaderManga implements java.io.Serializable {

	private ReaderMangaId id;

	public ReaderManga() {
	}

	public ReaderManga(ReaderMangaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", nullable = false)),
			@AttributeOverride(name = "idManga", column = @Column(name = "id_manga", nullable = false)) })
	public ReaderMangaId getId() {
		return this.id;
	}

	public void setId(ReaderMangaId id) {
		this.id = id;
	}

}
